// Code generated by go generate ./runcredential; DO NOT EDIT.

package runcredential

// fixtureKeys are the DER SubjectPublicKeyInfo, in standard base64, of the contract's
// published fixture keys: rs256.pem, es256.pem and eddsa.pem of the known answers of
// the run credential. Their seed is public, so [Key.PublicKey] refuses each.
var fixtureKeys = []string{
	"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtOzxba6Ydg9A31uMr8P7dTQXqmcAlII65n8oRtIQAqlnVmCTBvcqzD7uDdQnOX2qPTpqX6jJmZlgfpBRJvxeALuRrXd0tGUf2JVdO2etSNAbdoh7wer9ge3CAj1ZVJ1ko9rUZ+YTvjgQHgJoRuHUhFYYGmm8S6kEM2fIo4aySiY3JbKgOul+nSakzXkgEHyrZvyfgKQ0nVIypgo9QqvkBsha5jDo3yuc160OI1KKsb7mKGYb5uItyjIEcjqqBI+kvppl2USqhkyKP/+H10960lqlGdd10hruBl/5gNYsGq9bpHW7cD1nVUVmwUbhxbmj4OOu14lj5zg8Y/mjtWkhGwIDAQAB",
	"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE2wS0Aj283etz1sWRPtL4QY4qBXtJi4a2RArZkHWt2Okk3nTTI2E22wvkDcKzAepKgRZFBL6GNjc2HYM96XDiew==",
	"MCowBQYDK2VwAyEA2pvD1PE2BJg8wX7QEzUx7jMc3XIkNiLix7tmbln87Qc=",
}
