// Package knownanswers writes the known answers of the run credential, the files of
// contracts/forager/v1/fixtures/known-answers/run-credentials: the fixture starter's
// keys, derived from a published seed, two configurations of the fixture starter, and
// run credentials signed under the keys, each with its outcome at a fixed now. It also
// writes runcredential/fixturekeys.go, the fixture keys' SubjectPublicKeyInfo, which
// package runcredential refuses outside its known-answer tests.
//
// Everything is derived with Go's standard library from the seed alone, and every
// signature is deterministic (RSASSA-PKCS1-v1_5, ECDSA by RFC 6979, Ed25519), so the
// files are the same on every run. go generate ./runcredential writes them, and the
// package's tests fail while the files differ from what Files returns.
package knownanswers

import (
	"bytes"
	"crypto"
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/elliptic"
	"crypto/hmac"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/asn1"
	"encoding/base64"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"go/format"
	"math/big"
	"strings"
)

// Now is the clock every outcome holds at, in seconds since the epoch: the clock the
// signed fixtures of the contract are replayed at.
const Now = 1700000000

// Seed is the fixture starter's seed, bytes 193 to 224.
func Seed() []byte {
	s := make([]byte, 32)
	for n := range s {
		s[n] = byte(193 + n)
	}
	return s
}

// derive is SHA-256 of the seed followed by the label's bytes and the counter, one
// byte.
func derive(seed []byte, label string, counter byte) []byte {
	h := sha256.New()
	h.Write(seed)
	h.Write([]byte(label))
	h.Write([]byte{counter})
	return h.Sum(nil)
}

// prime is the first prime p at or above a candidate of 1024 bits, the candidate being
// SHA-256 of the seed, the label and the counters 0 to 3 concatenated, with its two
// highest bits and its lowest bit set, searched upward in steps of two, such that
// p - 1 is not a multiple of 65537.
func prime(seed []byte, label string) *big.Int {
	var b []byte
	for c := range byte(4) {
		b = append(b, derive(seed, label, c)...)
	}
	b[0] |= 0xc0
	b[len(b)-1] |= 1
	p := new(big.Int).SetBytes(b)
	e := big.NewInt(65537)
	two := big.NewInt(2)
	one := big.NewInt(1)
	for {
		if p.ProbablyPrime(32) {
			pm1 := new(big.Int).Sub(p, one)
			if new(big.Int).Mod(pm1, e).Sign() != 0 {
				return p
			}
		}
		p.Add(p, two)
	}
}

// Keys are the fixture starter's private keys.
type Keys struct {
	RSA     *rsa.PrivateKey
	ECDSA   *ecdsa.PrivateKey
	Ed25519 ed25519.PrivateKey
}

// DeriveKeys derives the fixture starter's keys from the seed:
//
//   - RSA: p is prime(seed, "rs256-p"), q is prime(seed, "rs256-q"), e is 65537, d is
//     the inverse of e modulo lcm(p-1, q-1), so the modulus has 2048 bits;
//   - ECDSA on P-256: the private scalar is SHA-256(seed || "es256" || 0x00), big
//     endian;
//   - Ed25519: the seed of the key is SHA-256(seed || "eddsa" || 0x00).
func DeriveKeys(seed []byte) (*Keys, error) {
	p, q := prime(seed, "rs256-p"), prime(seed, "rs256-q")
	if p.Cmp(q) == 0 {
		return nil, fmt.Errorf("p equals q")
	}
	one := big.NewInt(1)
	pm1, qm1 := new(big.Int).Sub(p, one), new(big.Int).Sub(q, one)
	g := new(big.Int).GCD(nil, nil, pm1, qm1)
	lambda := new(big.Int).Div(new(big.Int).Mul(pm1, qm1), g)
	e := big.NewInt(65537)
	d := new(big.Int).ModInverse(e, lambda)
	if d == nil {
		return nil, fmt.Errorf("e has no inverse")
	}
	rk := &rsa.PrivateKey{
		PublicKey: rsa.PublicKey{N: new(big.Int).Mul(p, q), E: 65537},
		D:         d,
		Primes:    []*big.Int{p, q},
	}
	if rk.N.BitLen() != 2048 {
		return nil, fmt.Errorf("the modulus has %d bits", rk.N.BitLen())
	}
	rk.Precompute()
	if err := rk.Validate(); err != nil {
		return nil, err
	}
	ek, err := ecdsa.ParseRawPrivateKey(elliptic.P256(), derive(seed, "es256", 0))
	if err != nil {
		return nil, err
	}
	return &Keys{RSA: rk, ECDSA: ek, Ed25519: ed25519.NewKeyFromSeed(derive(seed, "eddsa", 0))}, nil
}

// FixtureKeys are the DER SubjectPublicKeyInfo of the fixture starter's public keys, in
// the order rs256.pem, es256.pem, eddsa.pem.
func FixtureKeys() ([][]byte, error) {
	k, err := DeriveKeys(Seed())
	if err != nil {
		return nil, err
	}
	var out [][]byte
	for _, pub := range []crypto.PublicKey{&k.RSA.PublicKey, &k.ECDSA.PublicKey, k.Ed25519.Public()} {
		der, err := x509.MarshalPKIXPublicKey(pub)
		if err != nil {
			return nil, err
		}
		out = append(out, der)
	}
	return out, nil
}

// FixtureKeysSource is the Go source of runcredential/fixturekeys.go: the variable
// fixtureKeys, the [FixtureKeys] in standard base64.
func FixtureKeysSource() ([]byte, error) {
	keys, err := FixtureKeys()
	if err != nil {
		return nil, err
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by go generate ./runcredential; DO NOT EDIT.\n\n")
	b.WriteString("package runcredential\n\n")
	b.WriteString("// fixtureKeys are the DER SubjectPublicKeyInfo, in standard base64, of the contract's\n")
	b.WriteString("// published fixture keys: rs256.pem, es256.pem and eddsa.pem of the known answers of\n")
	b.WriteString("// the run credential. Their seed is public, so [Key.PublicKey] refuses each.\n")
	b.WriteString("var fixtureKeys = []string{\n")
	for _, der := range keys {
		fmt.Fprintf(&b, "\t%q,\n", base64.StdEncoding.EncodeToString(der))
	}
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}

// PEM is a public key as one PEM block of type PUBLIC KEY.
func PEM(pub crypto.PublicKey) ([]byte, error) {
	der, err := x509.MarshalPKIXPublicKey(pub)
	if err != nil {
		return nil, err
	}
	return pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: der}), nil
}

// The fixture starter: Issuer is its "issuer" key, the iss of its run credentials.
const (
	Issuer   = "https://issuer.example"
	Audience = "qory-gateway"
)

// configuration is a run credentials document of the fixture starter with the keys
// given, its public_key_file names relative to the directory of the known answers.
func configuration(algorithms []string, keys []map[string]string) []map[string]any {
	return []map[string]any{{
		"issuer":       Issuer,
		"audience":     Audience,
		"algorithms":   algorithms,
		"keys":         keys,
		"leeway":       "60s",
		"max_lifetime": "1h",
		"allow":        map[string]any{"claim": "namespace", "values": []string{"example-namespace"}},
		"labels": map[string]any{
			"forge":      map[string]string{"value": "example-forge"},
			"repository": map[string]any{"claims": []string{"namespace", "project"}, "join": "/"},
			"run_key":    map[string]string{"claim": "sub"},
		},
		"details": map[string]any{"requester": map[string]string{"claim": "requester"}},
	}}
}

// Case is one run credential and its outcome.
type Case struct {
	Name          string `json:"name"`
	Configuration string `json:"configuration"`
	Credential    string `json:"credential"`
	// Outcome is accepted or refused.
	Outcome string `json:"outcome"`
	// RefusedAt is the step that refuses a refused run credential: header, signature,
	// claims, scope or mapping.
	RefusedAt string            `json:"refused_at,omitempty"`
	Labels    map[string]string `json:"labels,omitempty"`
	Details   map[string]string `json:"details,omitempty"`
	Note      string            `json:"note"`
}

// claims are the claims of a valid run credential at [Now], with changes: a nil value
// removes the claim.
func claims(changes map[string]any) map[string]any {
	c := map[string]any{
		"iss":       Issuer,
		"aud":       Audience,
		"sub":       "rk-0001",
		"iat":       Now - 60,
		"exp":       Now + 600,
		"namespace": "example-namespace",
		"project":   "project",
		"requester": "example-requester",
	}
	for k, v := range changes {
		if v == nil {
			delete(c, k)
		} else {
			c[k] = v
		}
	}
	return c
}

var b64 = base64.RawURLEncoding

// segment is the base64url of a JSON object, its members sorted by name.
func segment(v any) string { return b64.EncodeToString(mustJSON(v)) }

// mustJSON is the JSON text of v, an object's members sorted by name.
func mustJSON(v any) []byte {
	b, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}
	return b
}

// signer signs the signing input of a JWS.
type signer func(input []byte) ([]byte, error)

// sign is the JWS compact serialisation of the header and claims under s; a nil s
// leaves the signature empty.
func sign(header, payload map[string]any, s signer) (string, error) {
	return signRaw(segment(header), segment(payload), s)
}

// signRaw is the JWS compact serialisation of the encoded header and payload under s.
func signRaw(header, payload string, s signer) (string, error) {
	input := header + "." + payload
	if s == nil {
		return input + ".", nil
	}
	sig, err := s([]byte(input))
	if err != nil {
		return "", err
	}
	return input + "." + b64.EncodeToString(sig), nil
}

// signatureChanged is s with its signature changed by change.
func signatureChanged(s signer, change func([]byte) []byte) signer {
	return func(input []byte) ([]byte, error) {
		sig, err := s(input)
		if err != nil {
			return nil, err
		}
		return change(sig), nil
	}
}

// p256Order is the order n of P-256's base point, 32 bytes, big endian.
func p256Order() []byte {
	return elliptic.P256().Params().N.FillBytes(make([]byte, 32))
}

// partChanged is a change to one part of a JWS compact serialisation.
func partChanged(n int, change func(string) string) func(string) string {
	return func(cred string) string {
		parts := strings.Split(cred, ".")
		parts[n] = change(parts[n])
		return strings.Join(parts, ".")
	}
}

// Files returns the known answers by file name.
func Files() (map[string][]byte, error) {
	k, err := DeriveKeys(Seed())
	if err != nil {
		return nil, err
	}
	rsaPEM, err := PEM(&k.RSA.PublicKey)
	if err != nil {
		return nil, err
	}
	ecPEM, err := PEM(&k.ECDSA.PublicKey)
	if err != nil {
		return nil, err
	}
	edPEM, err := PEM(k.Ed25519.Public())
	if err != nil {
		return nil, err
	}
	rs256 := func(input []byte) ([]byte, error) {
		h := sha256.Sum256(input)
		return rsa.SignPKCS1v15(nil, k.RSA, crypto.SHA256, h[:])
	}
	es256 := func(input []byte) ([]byte, error) {
		h := sha256.Sum256(input)
		der, err := k.ECDSA.Sign(nil, h[:], crypto.SHA256)
		if err != nil {
			return nil, err
		}
		return rawECDSA(der)
	}
	eddsa := func(input []byte) ([]byte, error) { return ed25519.Sign(k.Ed25519, input), nil }
	hs256 := func(input []byte) ([]byte, error) {
		m := hmac.New(sha256.New, rsaPEM)
		m.Write(input)
		return m.Sum(nil), nil
	}

	accepted := map[string]string{"forge": "example-forge", "repository": "example-namespace/project", "run_key": "rk-0001"}
	details := map[string]string{"requester": "example-requester"}
	type spec struct {
		name, config string
		header       map[string]any
		payload      map[string]any
		sign         signer
		refusedAt    string
		note         string
		// rawHeader and rawPayload, when set, are the JSON text of the header and the
		// payload in place of header and payload, for a member name twice.
		rawHeader, rawPayload string
		// change, when set, changes the run credential after it is signed.
		change func(string) string
	}
	// p is a spec of the fields every run credential has.
	p := func(name, config string, header, payload map[string]any, sign signer, refusedAt, note string) spec {
		return spec{name: name, config: config, header: header, payload: payload, sign: sign, refusedAt: refusedAt, note: note}
	}
	one := "one-key.json"
	two := "two-keys.json"
	hRS := map[string]any{"alg": "RS256", "typ": "JWT"}
	hES := map[string]any{"alg": "ES256", "typ": "JWT", "kid": "k-es256"}
	hEd := map[string]any{"alg": "EdDSA", "typ": "JWT", "kid": "k-eddsa"}
	specs := []spec{
		p("rs256", one, hRS, claims(nil), rs256, "", "RS256 under the one key, which has no kid; the credential carries none"),
		p("rs256-aud-array", one, hRS, claims(map[string]any{"aud": []string{"another-service", Audience}}), rs256, "", "aud is an array that contains the audience"),
		p("rs256-expired-within-leeway", one, hRS, claims(map[string]any{"iat": Now - 630, "exp": Now - 30}), rs256, "", "exp passed 30 seconds ago, within the leeway of 60 seconds"),
		p("rs256-no-requester", one, hRS, claims(map[string]any{"requester": nil}), rs256, "", "no requester: the run credential does not decide about.details.requester, and the session's value stands"),
		p("requester-not-string", one, hRS, claims(map[string]any{"requester": 7}), rs256, "mapping", "requester is a number, not the string details needs"),
		p("project-control-character", one, hRS, claims(map[string]any{"project": "project\nother"}), rs256, "mapping", "project, a claim of the label repository, holds a line feed, a control character"),
		p("es256", two, hES, claims(nil), es256, "", "ES256 under the key k-es256, the signature R and S, 32 bytes each"),
		p("eddsa", two, hEd, claims(nil), eddsa, "", "EdDSA under the Ed25519 key k-eddsa"),
		p("alg-none", one, map[string]any{"alg": "none", "typ": "JWT"}, claims(nil), nil, "header", "alg none, with an empty signature"),
		p("hs256-public-key-as-secret", one, map[string]any{"alg": "HS256", "typ": "JWT"}, claims(nil), hs256, "header", "HS256 with the PEM bytes of the RSA public key, rs256.pem, as the HMAC secret: the confusion of algorithms"),
		p("kid-not-pinned", one, map[string]any{"alg": "RS256", "typ": "JWT", "kid": "k-rs256"}, claims(nil), rs256, "header", "a kid, and the one key pinned has none"),
		p("kid-unknown", two, map[string]any{"alg": "ES256", "typ": "JWT", "kid": "k-unknown"}, claims(nil), es256, "header", "a kid no pinned key has"),
		p("no-kid-two-keys", two, map[string]any{"alg": "ES256", "typ": "JWT"}, claims(nil), es256, "header", "no kid, and the starter pins two keys"),
		p("alg-differs-from-key", two, map[string]any{"alg": "EdDSA", "typ": "JWT", "kid": "k-es256"}, claims(nil), eddsa, "header", "alg EdDSA, signed with the Ed25519 key, and a kid that selects the ES256 key"),
		p("alg-not-allowed", two, map[string]any{"alg": "RS256", "typ": "JWT", "kid": "k-es256"}, claims(nil), rs256, "header", "RS256, which is not among the algorithms of this configuration"),
		p("crit", one, map[string]any{"alg": "RS256", "typ": "JWT", "crit": []string{"exp"}}, claims(nil), rs256, "header", "crit names an extension the gateway does not understand"),
		p("aud-other", one, hRS, claims(map[string]any{"aud": "another-service"}), rs256, "claims", "aud is another service's"),
		p("iss-other", one, hRS, claims(map[string]any{"iss": "https://other-issuer.example"}), rs256, "claims", "iss is not the starter's"),
		p("expired", one, hRS, claims(map[string]any{"iat": Now - 720, "exp": Now - 120}), rs256, "claims", "exp passed 120 seconds ago, beyond the leeway"),
		p("iat-future", one, hRS, claims(map[string]any{"iat": Now + 120, "exp": Now + 720}), rs256, "claims", "iat is 120 seconds ahead, beyond the leeway"),
		p("lifetime-above-max", one, hRS, claims(map[string]any{"iat": Now - 60, "exp": Now - 60 + 7200}), rs256, "claims", "exp minus iat is two hours, above max_lifetime of one hour"),
		p("no-iat", one, hRS, claims(map[string]any{"iat": nil}), rs256, "claims", "no iat, and max_lifetime is set"),
		p("no-sub", one, hRS, claims(map[string]any{"sub": nil}), rs256, "claims", "no sub, the run key"),
		p("namespace-not-allowed", one, hRS, claims(map[string]any{"namespace": "other-namespace"}), rs256, "scope", "namespace holds a value allow does not list"),
		{name: "rs256-typ-lower-case", config: one, header: map[string]any{"alg": "RS256", "typ": "jwt"}, payload: claims(nil), sign: rs256,
			note: "typ jwt: typ is compared without regard to case"},
		{name: "rs256-no-typ", config: one, header: map[string]any{"alg": "RS256"}, payload: claims(nil), sign: rs256,
			note: "no typ, which is optional"},
		{name: "typ-other", config: one, header: map[string]any{"alg": "RS256", "typ": "at+jwt"}, payload: claims(nil), sign: rs256, refusedAt: "header",
			note: "typ is at+jwt, not JWT"},
		{name: "header-member-twice", config: one, rawHeader: `{"alg":"RS256","alg":"RS256","typ":"JWT"}`, payload: claims(nil), sign: rs256, refusedAt: "header",
			note: "the header names alg twice, with the same value, and is signed: a header with a member name twice is refused"},
		{name: "es256-signature-63-bytes", config: two, header: hES, payload: claims(nil), refusedAt: "signature",
			sign: signatureChanged(es256, func(b []byte) []byte { return b[:63] }), note: "the ES256 signature of es256 less its last byte: 63 bytes, not 64"},
		{name: "es256-signature-65-bytes", config: two, header: hES, payload: claims(nil), refusedAt: "signature",
			sign: signatureChanged(es256, func(b []byte) []byte { return append(b, 0) }), note: "the ES256 signature of es256 and a zero byte: 65 bytes, not 64"},
		{name: "es256-r-zero", config: two, header: hES, payload: claims(nil), refusedAt: "signature",
			sign: signatureChanged(es256, func(b []byte) []byte { return append(make([]byte, 32), b[32:]...) }), note: "the ES256 signature of es256 with R zero, outside [1, n-1]"},
		{name: "es256-s-order", config: two, header: hES, payload: claims(nil), refusedAt: "signature",
			sign: signatureChanged(es256, func(b []byte) []byte { return append(b[:32:32], p256Order()...) }), note: "the ES256 signature of es256 with S the order n of P-256, outside [1, n-1]"},
		{name: "header-altered", config: one, header: hRS, payload: claims(nil), sign: rs256, refusedAt: "signature",
			change: partChanged(0, func(string) string { return segment(map[string]any{"alg": "RS256", "typ": "jwt"}) }),
			note:   "signed with the header of rs256, sent with typ jwt: every step but the signature accepts it"},
		{name: "padding", config: one, header: hRS, payload: claims(nil), sign: rs256, refusedAt: "serialisation",
			change: partChanged(2, func(p string) string { return p + "==" }), note: "rs256 with its signature's base64url padded with ==, which base64url without padding refuses"},
		{name: "line-feed", config: one, header: hRS, payload: claims(nil), sign: rs256, refusedAt: "serialisation",
			change: partChanged(1, func(p string) string { return p[:10] + "\n" + p[10:] }), note: "rs256 with a line feed inside its payload's base64url, which a lenient decoder skips"},
		{name: "space", config: one, header: hRS, payload: claims(nil), sign: rs256, refusedAt: "serialisation",
			change: func(c string) string { return c + " " }, note: "rs256 followed by a space"},
		{name: "four-parts", config: one, header: hRS, payload: claims(nil), sign: rs256, refusedAt: "serialisation",
			change: func(c string) string { return c + "." + strings.Split(c, ".")[2] }, note: "rs256 and its signature again after another dot: four parts"},
		{name: "two-parts", config: one, header: hRS, payload: claims(nil), sign: rs256, refusedAt: "serialisation",
			change: func(c string) string { return c[:strings.LastIndex(c, ".")] }, note: "the header and payload of rs256 alone: two parts"},
		{name: "no-exp", config: one, header: hRS, payload: claims(map[string]any{"exp": nil}), sign: rs256, refusedAt: "claims",
			note: "no exp, which is required"},
		{name: "no-aud", config: one, header: hRS, payload: claims(map[string]any{"aud": nil}), sign: rs256, refusedAt: "claims",
			note: "no aud, which is required"},
		{name: "payload-member-twice", config: one, header: hRS, rawPayload: `{"sub":"rk-0002",` + strings.TrimPrefix(string(mustJSON(claims(nil))), "{"), sign: rs256, refusedAt: "claims",
			note: "the payload names sub twice, and is signed: a payload with a member name twice is refused"},
	}
	var cases []Case
	for _, s := range specs {
		header, payload := s.rawHeader, s.rawPayload
		if header == "" {
			header = string(mustJSON(s.header))
		}
		if payload == "" {
			payload = string(mustJSON(s.payload))
		}
		cred, err := signRaw(b64.EncodeToString([]byte(header)), b64.EncodeToString([]byte(payload)), s.sign)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", s.name, err)
		}
		if s.change != nil {
			cred = s.change(cred)
		}
		c := Case{Name: s.name, Configuration: s.config, Credential: cred, Outcome: "accepted", Note: s.note}
		if s.refusedAt != "" {
			c.Outcome, c.RefusedAt = "refused", s.refusedAt
		} else {
			c.Labels, c.Details = accepted, details
			if _, ok := s.payload["requester"]; !ok {
				c.Details = nil
			}
		}
		cases = append(cases, c)
	}
	// The signature over an altered payload: signed over the valid claims, then sent
	// with a project changed, which every step but the signature accepts.
	orig, err := sign(hRS, claims(nil), rs256)
	if err != nil {
		return nil, err
	}
	parts := bytes.Split([]byte(orig), []byte("."))
	altered := string(parts[0]) + "." + segment(claims(map[string]any{"project": "other-project"})) + "." + string(parts[2])
	cases = append(cases, Case{Name: "payload-altered", Configuration: one, Credential: altered, Outcome: "refused", RefusedAt: "signature",
		Note: "signed over the claims of rs256, sent with project other-project: every step but the signature accepts it"})

	keysDoc := map[string]any{
		"note": "The fixture starter, " + Issuer + ", and its keys, derived from the seed, bytes 193 to 224, in base64url. " +
			"RSA: p is the first prime at or above the 1024-bit number SHA-256(seed || \"rs256-p\" || 0x00) || ... || SHA-256(seed || \"rs256-p\" || 0x03) with its two highest bits and its lowest bit set, searched upward in steps of two, with p - 1 not a multiple of 65537; q the same with \"rs256-q\"; e is 65537. " +
			"ECDSA on P-256: the private scalar is SHA-256(seed || \"es256\" || 0x00), big endian. " +
			"Ed25519: the key's seed is SHA-256(seed || \"eddsa\" || 0x00). " +
			"Each public key is the PEM file named, a PKIX SubjectPublicKeyInfo. These keys are public: anyone can derive their private keys from the seed. Forager refuses each in a configuration; never pin them.",
		"seed": b64.EncodeToString(Seed()),
		"keys": []map[string]string{
			{"kid": "k-rs256", "alg": "RS256", "public_key_file": "rs256.pem", "note": "pinned without a kid in one-key.json"},
			{"kid": "k-es256", "alg": "ES256", "public_key_file": "es256.pem"},
			{"kid": "k-eddsa", "alg": "EdDSA", "public_key_file": "eddsa.pem"},
		},
	}
	index := map[string]any{
		"note": "Run credentials of the fixture starter, each with its outcome at now, under the configuration named, a file beside this one. " +
			"refused_at is the step that refuses one: serialisation, anything but exactly three parts of base64url without padding, white space or a byte outside its alphabet; header, a header that is not one JSON object with each member name once, a crit, a typ other than JWT, compared without regard to case, and the alg and the key the header selects; signature, over the exact bytes received, an ES256 signature exactly 64 bytes with R and S each in [1, n-1]; claims, a payload that is not one JSON object with each member name once, the time, iss, aud and sub; scope, allow; mapping, a claim the labels or details name that is present and not a string, or that holds a control character. " +
			"A details claim the credential does not carry leaves that key undecided, and the session's value stands; a label claim it does not carry refuses it. " +
			"A credential refused at a later step passes every earlier one, and an accepted one passes every step, the signature included, with the labels and details listed. " +
			"Every refusal is the same opaque answer: run_credential_refused to a session, 407 to a client with no session.",
		"now":         Now,
		"credentials": cases,
	}
	files := map[string][]byte{
		"rs256.pem": rsaPEM,
		"es256.pem": ecPEM,
		"eddsa.pem": edPEM,
	}
	for name, v := range map[string]any{
		"keys.json":        keysDoc,
		"credentials.json": index,
		one:                configuration([]string{"RS256"}, []map[string]string{{"alg": "RS256", "public_key_file": "rs256.pem"}}),
		two: configuration([]string{"ES256", "EdDSA"}, []map[string]string{
			{"kid": "k-es256", "alg": "ES256", "public_key_file": "es256.pem"},
			{"kid": "k-eddsa", "alg": "EdDSA", "public_key_file": "eddsa.pem"},
		}),
	} {
		b, err := json.MarshalIndent(v, "", "  ")
		if err != nil {
			return nil, err
		}
		files[name] = append(b, '\n')
	}
	return files, nil
}

// rawECDSA turns an ASN.1 ECDSA signature into R and S, 32 bytes each, big endian, as
// RFC 7518 §3.4 writes ES256.
func rawECDSA(der []byte) ([]byte, error) {
	var sig struct{ R, S *big.Int }
	if _, err := asn1.Unmarshal(der, &sig); err != nil {
		return nil, err
	}
	out := make([]byte, 64)
	sig.R.FillBytes(out[:32])
	sig.S.FillBytes(out[32:])
	return out, nil
}
